### ISSUE TITLE
error in the export for dbfiles

### ISSUE THREAD

**Issue by arademaker** [own-pt/mill#48] opened 2020-02-11 01:12 UTC
```
% mill export -c config -l en --wndb src ~/Temp/tt
mill: No head or more than one head
CallStack (from HasCallStack):
  error, called at src/Export.hs:305:25 in mill-0.1.0.0-H0ExyKEE7Io8CVBxpaTfTx:Export
```

@odanoburu any idea? We need to generate the DB files to produce the Freeling files from OWN-EN... Can you help?

**Comment by odanoburu** [comment] 2020-02-11 01:18
is the validate command reporting any errors? the error is caused by a satellite adjective missing a head synset or having more than one head… I'll fix the error message tomorrow so that it reports the offending synset.

Feb 10, 2020, 22:12 by notifications@github.com:

**Comment by alexandretessarollo** [comment] 2020-02-11 02:13
> is the validate command reporting any errors? the error is caused by a satellite adjective missing a head synset or having more than one head… I'll fix the error message tomorrow so that it reports the offending synset. Feb 10, 2020, 22:12 by notifications@github.com:
> […](#)

I've got the same error message here. We didn't touch the adjectives, only noun.substance and noun.cognitive. There shouldn't be any adjective issue.

**Comment by alexandretessarollo** [comment] 2020-02-11 02:23
Went back in history to get the original files for noun.cognition and noun.substance and then tried to run the export again. Same error:

mill: No head or more than one head
CallStack (from HasCallStack):
  error, called at src/Export.hs:305:25 in mill-0.1.0.0-H0ExyKEE7Io8CVBxpaTfTx:Export

It created this files before crashing:
[export_files.zip](https://github.com/own-pt/mill/files/4183892/export_files.zip)

**Comment by odanoburu** [comment] 2020-02-11 12:14
ok, I know what the problem is: when we made similarTo relations one-way to be able to identify which adjective synsets are satellites, we kept these relations as head->satellite and not satellite->head; this validation error complains about multiple heads, but it actually is a symptom of several satellites (which is fine). is it OK if we actually keep these relations as satellite->head? is there a reason not to? (it makes the export easier)

I've fixed the error message, but it's not really related to the core of the problem.

**Comment by arademaker** [comment] 2020-02-11 12:41
In https://wordnet.princeton.edu/documentation/wninput5wn  it is confusing. The `similar to` is reflexive but also they say:

> Head and satellite synsets follow the syntax of basic synsets, however a "Similar to" pointer must be specified in a head synset for each of its satellite synsets. 

So I don't know clearly the implications of this change. Surely we would have to document it very well somehow. This is the kind of change that will cause confusion in the feature. Imagine exporting the data and comparing it with other resources?

**Comment by odanoburu** [comment] 2020-02-11 13:13
yes, but we can (and I think we do, but I don't really remember now) introduce the reflexivity during the export.

this will not change the WNDB format, just the mill lexicographer files.

**Comment by arademaker** [comment] 2020-02-18 20:28
No error in the validation 

```
% mill export -c config -l en --wndb src ~/Temp
mill: More than one head synset in synset en-adj.all-abnormal-2
CallStack (from HasCallStack):
  error, called at src/Export.hs:306:25 in mill-0.1.0.0-H0ExyKEE7Io8CVBxpaTfTx:Export
ar@leme own-en % mill validate -c config -l en src
ar@leme own-en %
```

But export still causing error!

**Comment by arademaker** [comment] 2020-02-18 20:28
Any idea @odanoburu ?

**Comment by arademaker** [comment] 2020-02-18 20:30
>  is it OK if we actually keep these relations as satellite->head? is there a reason not to? (it makes the export easier)

But this makes our model different from PWN and it makes our life harder to convince people later... Can we follow the original relation model?

**Comment by odanoburu** [comment] 2020-02-18 20:53
> But export still causing error!

yes, it's not fixed yet.

we made `similarTo` one-way because we needed to be able to distinguish between head and satellite adjectives (since we don't differentiate between them syntactically like the PWN does). anything that distinguishes them can be a solution, if you don't like this one. off the top of my head, we can:

- keep it one way and fix the exports;
- make it reflexive but give each way a different name (satellites have a `head` relation, heads have a `satellite` relation)
- make it reflexive, and add a dummy relation to mark if synset is a head or a satellite.

**Comment by arademaker** [comment] 2020-02-20 22:07
> since we don't differentiate between them syntactically like the PWN does

why?

**Comment by odanoburu** [comment] 2020-02-21 01:02
> why?

when you and Chalub developed the basic idea of the format you did not differentiate between head and satellite synsets (which I think makes a lot of sense). but you still had the same problem we have now, i.e., we can't know if an adjective synset is a head or a satellite by just looking at their definition. you solved it by putting all satellites in their own lexicographer file (the new `adjs.all`), but that caused other problems of incompatibility with PWN.

I reiterate my [previous comment](https://github.com/own-pt/mill/issues/48#issuecomment-587830332) with possible solutions (and I'm open to hearing if you have any others), plus I add that the easiest/fastest solution is to have `similarTo` relations in both heads and satellites, but give them different names; this is even arguably the best solution.

**Comment by arademaker** [comment] 2020-02-24 15:05
any solution different from the current similarTo one way will need to change the data, right? So let us fix the exporting by keep the semantics of similarTo as one way relation satellite to head.

So we can close this issue and in the future, if needed, we open an issue for consistent change the relation and export. Make sense?

**Comment by odanoburu** [comment] 2020-02-24 23:03
ok, https://github.com/own-pt/own-en/pull/3 should help. WNDB export should be working now, make sure you have the latest versions of all repositories and that you delete the `.cache` directories in the source directories.

I used the script at `python/roundtrip.py` to make the change, and it ended up being added to the repository as an example of how to edit the WN programmatically using Python. 

note: I could have introduced the change in the bootstrap script (which is a better idea), but then we would introduce spurious diffs since the algorithm that decides the target lexical forms of synset relations is not guaranteed to be deterministic.

**Comment by arademaker** [comment] 2020-02-25 21:39
thank you. exportation for DB and JSON worked. In what situations I need to manually delete the `.cache` directory?

**Comment by odanoburu** [comment] 2020-02-25 21:46
it's as they say

> There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.

whenever there's a change in the internal data structure the cache will be invalidated, for example. but as a rule of thumb I'd say that if there's a problem (any problem) try deleting the cache before anything else.

**Comment by arademaker** [comment] 2020-02-25 22:11
Maybe the wiki can describe the `.cache` and what is saved there.

**Closed** 2020-02-25 22:11 UTC

**Comment by odanoburu** [comment] 2020-02-25 22:28
done, at https://github.com/own-pt/mill/wiki/Validation

**Comment by arademaker** [comment] 2020-02-25 22:43
Sorry, but we need a better definition for internal structure. What is the internal structure? Relations? DSL grammar?

> whenever there is a change in the internal structure

**Comment by odanoburu** [comment] 2020-02-26 21:04
I'll try to rephrase, I'm trying to avoid leaking unnecessary details to the end-users

**Comment by arademaker** [comment] 2020-02-26 22:19
No need for avoiding technical details. We do need them documented. In the future we may split docs if needed.
